version: "3"

services:
  rssc:
    image: soulteary/rss-can:v0.3.7
    environment:
      - RSS_SERVER=redis:6379
    ports:
      - "8080:8080"
    volumes:
      - ./rules:/rules

  # If Redis Cache is enabled, then any version of Redis is necessary,
  # or a cloud server can be used instead
  redis:
    image: redis:alpine
