project_name: RSS-Can

builds:
  - <<: &build_defaults
      env:
        - CGO_ENABLED=1
      ldflags:
        - -w -s -X "github.com/soulteary/RSS-Can/internal/version.Version={{ .Tag }}" -X "github.com/soulteary/RSS-Can/internal/version.Commit={{.Commit}}" -X "github.com/soulteary/RSS-Can/internal/version.BuildDate={{.Date}}"
    id: macos
    goos: [ darwin ]
    goarch: [ amd64, arm64 ]

  - <<: *build_defaults
    id: linux
    goos: [linux]
    goarch: [amd64, arm64]
    goarm:
      - "7"
      - "6"

dockers:

  - image_templates:
      - "soulteary/RSS-Can:linux-amd64-{{ .Tag }}"
      - "soulteary/RSS-Can:linux-amd64"
    dockerfile: docker/goreleaser/Dockerfile.amd64
    use: buildx
    goarch: amd64
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description={{ .ProjectName }}"
      - "--label=org.opencontainers.image.url=https://github.com/soulteary/RSS-Can"
      - "--label=org.opencontainers.image.source=https://github.com/soulteary/RSS-Can"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=MIT"

  - image_templates:
      - "soulteary/RSS-Can:linux-arm64-{{ .Tag }}"
      - "soulteary/RSS-Can:linux-arm64"
    dockerfile: docker/goreleaser/Dockerfile.arm64v8
    use: buildx
    goos: linux
    goarch: arm64
    goarm: ''
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description={{ .ProjectName }}"
      - "--label=org.opencontainers.image.url=https://github.com/soulteary/RSS-Can"
      - "--label=org.opencontainers.image.source=https://github.com/soulteary/RSS-Can"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=MIT"

docker_manifests:
  - name_template: "soulteary/RSS-Can:{{ .Tag }}"
    image_templates:
      - "soulteary/RSS-Can:linux-amd64-{{ .Tag }}"
      - "soulteary/RSS-Can:linux-arm64-{{ .Tag }}"
    skip_push: "false"

  - name_template: "soulteary/RSS-Can:latest"
    image_templates:
      - "soulteary/RSS-Can:linux-amd64-{{ .Tag }}"
      - "soulteary/RSS-Can:linux-arm64-{{ .Tag }}"
    skip_push: "false"