name: Feature request
description: Suggest an idea for this project
labels:
  - feature / 新功能 🎁
  - judge / 悬而未决 🥷
assignees:
  - soulteary
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your interest in RSS Can, please fill out the form below with your ideas.
  - type: textarea
    id: is-it-a-problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
  - type: checkboxes
    id: search
    attributes:
      label: confirm
      options:
        - label: Before submitting this form, I have searched for related issues and found no related issues or solutions.
          required: true
  - type: textarea
    id: ctx
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false