name: 功能建议
description: 请求添加一个功能，或者建议对现有功能进行完善
labels:
  - feature / 新功能 🎁
  - judge / 悬而未决 🥷
assignees:
  - soulteary
body:
  - type: markdown
    attributes:
      value: |
        感谢你对于 RSS Can 感兴趣，请根据你的想法填写下面的表格。
  - type: textarea
    id: is-it-a-problem
    attributes:
      label: 请描述你为什么要申请这个功能，是在使用的过程中遇到了什么问题嘛？
      description: 请对你遇到的问题进行简单、清晰的描述。
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: 请描述你想要得到的结果
      description: 对你想要的结果进行清晰的描述。
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: 请描述你想要的替代方案
      description: 对你想要的替代方案进行清晰的描述。
    validations:
      required: true
  - type: checkboxes
    id: search
    attributes:
      label: 搜索
      options:
        - label: 在提交这个表格之前，我已经进行了相关问题搜索，没有找到相关的问题或解决方案。
          required: true
  - type: textarea
    id: ctx
    attributes:
      label: 补充描述
      description: 可以在这里填写要补充的内容
    validations:
      required: false